### PR TITLE
Compat & Dodge Chance

### PR DESCRIPTION
**Pull request by oorzkws**
Hi, I'm the guy that commented on the workshop page asking about compatibility for a gene mod. This PR makes the `VariedBodySizesModSettings` public so harmony patches can modify the fields.

The second commit adds a dodge chance inverse to body size, but you're welcome to reject it if you see it as unnecessary. I also don't have the translation for the added keys - if you have a workflow for translating I would appreciate it, otherwise I'll see about throwing the text through DeepL or the like.

### CODE REVIEW

**Comment by oorzkws** [comment]
Just as a sidenote, I'm *very* new to RimWorld modding so my patches may be done in a strange fashion - there may be obvious mistakes I'm unaware of.

Edit: [Here](https://github.com/oorzkws/rimworld-bodysizegenes/blob/master/Source/genebodysize/HarmonyPatches.cs#L16) is the source for the patches I'm doing to the settings

**Comment by oorzkws** [comment]
P.S. Vanilla Expanded Framework appears to break pawn scaling with a transpiler - with it active only heads scale. Going to see if I can track down why and fix it.

Edit: After much screaming, I have a workaround. Unfortunately, this is very version-specific for VE until they find and fix their problem with scaling.

**Comment by emipa606** [comment]
Nice work! Should be added in b5fce6d

**Comment by oorzkws** [comment]
Oh dear, I appear to have caused you some grief. The issue only appears with caravan animals it seems, I'm working on it

**Pull request merged**
